import json
import os

cells = []

# ==========================================================
# CELL 1: Environment Setup
# ==========================================================
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Cell 1: Environment Setup\n",
        "# Set up folders for databases, assessments, document storage, and RAG knowledge folders\n",
        "import os\n",
        "import sys\n",
        "\n",
        "print('Setting up directory structure...')\n",
        "folders = [\n",
        "    'data', 'data/assessments', 'data/documents', 'reports', 'data/faiss_index', 'prompts',\n",
        "    'knowledge_base', 'knowledge_base/psychology', 'knowledge_base/cbt', 'knowledge_base/guidelines', 'knowledge_base/assessments'\n",
        "]\n",
        "for folder in folders:\n",
        "    os.makedirs(folder, exist_ok=True)\n",
        "    print(f'Directory ready: {folder}/')\n",
        "\n",
        "print('\\nSystem setup complete. RAG knowledge folders initialized.')\n"
    ]
})

# ==========================================================
# CELL 2: Install Dependencies
# ==========================================================
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Cell 2: Install Dependencies\n",
        "# Install LangChain, FAISS, sentence-transformers, PyPDF, ReportLab, and Gemini API\n",
        "\n",
        "!pip install -q streamlit google-genai groq sentence-transformers faiss-cpu pypdf reportlab plotly pyngrok langchain langchain-community langchain-huggingface\n",
        "print('Dependencies installed successfully.')\n"
    ]
})

# ==========================================================
# CELL 3: Configuration & Database Setup
# ==========================================================
cell_3_lines = [
    "# Cell 3: Configuration & Database Setup\n",
    "# Create config.py and database.py files and initialize the SQLite database\n",
    "\n",
    "with open('config.py', 'w', encoding='utf-8') as f:\n",
    "    f.write('''import os\n",
    "DB_TYPE = \"sqlite\"\n",
    "SQLITE_PATH = \"data/mental_health_platform.db\"\n",
    "SUPABASE_URL = os.environ.get(\"SUPABASE_URL\", \"https://your-project.supabase.co\")\n",
    "SUPABASE_KEY = os.environ.get(\"SUPABASE_KEY\", \"your-supabase-anon-key\")\n",
    "GEMINI_API_KEY = os.environ.get(\"GEMINI_API_KEY\", \"\")\n",
    "GROQ_API_KEY = os.environ.get(\"GROQ_API_KEY\", \"\")\n",
    "ROLE_PATIENT = \"patient\"\n",
    "ROLE_PSYCHOLOGIST = \"psychologist\"\n",
    "ROLE_ADMIN = \"admin\"\n",
    "PROMPTS_DIR = \"prompts\"\n",
    "''')\n",
    "\n",
    "with open('database.py', 'w', encoding='utf-8') as f:\n",
    "    f.write('''import sqlite3\n",
    "import os\n",
    "from datetime import datetime\n",
    "import config\n",
    "\n",
    "def get_connection():\n",
    "    if config.DB_TYPE == \"sqlite\":\n",
    "        conn = sqlite3.connect(config.SQLITE_PATH)\n",
    "        conn.row_factory = sqlite3.Row\n",
    "        return conn\n",
    "    else:\n",
    "        raise NotImplementedError(\"Supabase connection logic not configured.\")\n",
    "\n",
    "def init_db():\n",
    "    conn = get_connection()\n",
    "    cursor = conn.cursor()\n",
    "    cursor.execute(\"PRAGMA foreign_keys = ON;\")\n",
    "    \n",
    "    cursor.execute(\"\"\"\n",
    "    CREATE TABLE IF NOT EXISTS users (\n",
    "        id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "        username TEXT UNIQUE NOT NULL,\n",
    "        password_hash TEXT NOT NULL,\n",
    "        role TEXT NOT NULL,\n",
    "        full_name TEXT NOT NULL,\n",
    "        email TEXT NOT NULL,\n",
    "        created_at TEXT DEFAULT CURRENT_TIMESTAMP\n",
    "    );\n",
    "    \"\"\")\n",
    "    \n",
    "    cursor.execute(\"\"\"\n",
    "    CREATE TABLE IF NOT EXISTS patients (\n",
    "        id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "        user_id INTEGER UNIQUE NOT NULL,\n",
    "        dob TEXT NOT NULL DEFAULT \\'\\',\n",
    "        age INTEGER DEFAULT 30,\n",
    "        gender TEXT NOT NULL DEFAULT \\'\\',\n",
    "        phone TEXT NOT NULL DEFAULT \\'\\',\n",
    "        consent_given INTEGER NOT NULL DEFAULT 0,\n",
    "        consent_date TEXT,\n",
    "        assigned_psychologist_id INTEGER,\n",
    "        created_at TEXT DEFAULT CURRENT_TIMESTAMP,\n",
    "        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,\n",
    "        FOREIGN KEY (assigned_psychologist_id) REFERENCES users(id)\n",
    "    );\n",
    "    \"\"\")\n",
    "    \n",
    "    cursor.execute(\"\"\"\n",
    "    CREATE TABLE IF NOT EXISTS assessment_sessions (\n",
    "        id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "        patient_id INTEGER NOT NULL,\n",
    "        assessment_name TEXT NOT NULL,\n",
    "        status TEXT NOT NULL CHECK (status IN (\\'started\\', \\'completed\\', \\'abandoned\\')),\n",
    "        score INTEGER,\n",
    "        severity TEXT,\n",
    "        risk_level TEXT DEFAULT \\'low\\',\n",
    "        safety_escalated INTEGER DEFAULT 0,\n",
    "        safety_notes TEXT DEFAULT \\'\\',\n",
    "        started_at TEXT NOT NULL,\n",
    "        completed_at TEXT,\n",
    "        FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE\n",
    "    );\n",
    "    \"\"\")\n",
    "    \n",
    "    cursor.execute(\"\"\"\n",
    "    CREATE TABLE IF NOT EXISTS assessment_responses (\n",
    "        id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "        session_id INTEGER NOT NULL,\n",
    "        question_id TEXT NOT NULL,\n",
    "        response_value INTEGER NOT NULL,\n",
    "        response_text TEXT NOT NULL,\n",
    "        created_at TEXT DEFAULT CURRENT_TIMESTAMP,\n",
    "        FOREIGN KEY (session_id) REFERENCES assessment_sessions(id) ON DELETE CASCADE\n",
    "    );\n",
    "    \"\"\")\n",
    "    \n",
    "    cursor.execute(\"\"\"\n",
    "    CREATE TABLE IF NOT EXISTS session_summaries (\n",
    "        id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "        session_id INTEGER UNIQUE NOT NULL,\n",
    "        summary_text TEXT NOT NULL,\n",
    "        clinician_notes TEXT NOT NULL,\n",
    "        action_items TEXT NOT NULL,\n",
    "        created_at TEXT DEFAULT CURRENT_TIMESTAMP,\n",
    "        FOREIGN KEY (session_id) REFERENCES assessment_sessions(id) ON DELETE CASCADE\n",
    "    );\n",
    "    \"\"\")\n",
    "    \n",
    "    cursor.execute(\"\"\"\n",
    "    CREATE TABLE IF NOT EXISTS chat_messages (\n",
    "        id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "        session_id INTEGER NOT NULL,\n",
    "        sender TEXT NOT NULL,\n",
    "        message TEXT NOT NULL,\n",
    "        timestamp TEXT DEFAULT CURRENT_TIMESTAMP,\n",
    "        FOREIGN KEY (session_id) REFERENCES assessment_sessions(id) ON DELETE CASCADE\n",
    "    );\n",
    "    \"\"\")\n",
    "    \n",
    "    cursor.execute(\"\"\"\n",
    "    CREATE TABLE IF NOT EXISTS audit_logs (\n",
    "        id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "        user_id INTEGER,\n",
    "        action TEXT NOT NULL,\n",
    "        target_table TEXT,\n",
    "        target_id INTEGER,\n",
    "        timestamp TEXT DEFAULT CURRENT_TIMESTAMP\n",
    "    );\n",
    "    \"\"\")\n",
    "    \n",
    "    cursor.execute(\"SELECT count(*) FROM users;\")\n",
    "    if cursor.fetchone()[0] == 0:\n",
    "        users_to_seed = [\n",
    "            (\\'admin\\', \\'240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9\\', \\'admin\\', \\'System Admin\\', \\'admin@careminds.ai\\'),\n",
    "            (\\'dr_smith\\', \\'c108533d4511b3e7263207ace80f6b4be9dd983898514f1dbc075c9b6a83bae1\\', \\'psychologist\\', \\'Dr. Smith\\', \\'smith@careminds.ai\\'),\n",
    "            (\\'john_doe\\', \\'d4587ea9ead060c13fd994f21ecfa7926272a78854a2c20136b10a3c9e53e71e\\', \\'patient\\', \\'John Doe\\', \\'johndoe@email.com\\')\n",
    "        ]\n",
    "        for username, password_hash, role, full_name, email in users_to_seed:\n",
    "            cursor.execute(\"\"\"\n",
    "            INSERT INTO users (username, password_hash, role, full_name, email)\n",
    "            VALUES (?, ?, ?, ?, ?);\n",
    "            \"\"\", (username, password_hash, role, full_name, email))\n",
    "            u_id = cursor.lastrowid\n",
    "            if role == \\'patient\\':\n",
    "                cursor.execute(\"\"\"\n",
    "                INSERT INTO patients (user_id, dob, age, gender, phone, consent_given, consent_date, assigned_psychologist_id)\n",
    "                VALUES (?, \\'1992-08-20\\', 33, \\'Male\\', \\'+15550199\\', 1, \\'2026-06-17 12:00:00\\', 2);\n",
    "                \"\"\", (u_id,))\n",
    "        print(\"Database seeded with default credentials.\")\n",
    "        \n",
    "    conn.commit()\n",
    "    conn.close()\n",
    "\n",
    "def log_audit(user_id, action, target_table=None, target_id=None):\n",
    "    try:\n",
    "        conn = get_connection()\n",
    "        cursor = conn.cursor()\n",
    "        cursor.execute(\"\"\"\n",
    "        INSERT INTO audit_logs (user_id, action, target_table, target_id)\n",
    "        VALUES (?, ?, ?, ?);\n",
    "        \"\"\", (user_id, action, target_table, target_id))\n",
    "        conn.commit()\n",
    "        conn.close()\n",
    "    except Exception as e:\n",
    "        print(f\"Audit log failed: {e}\")\n",
    "''')\n",
    "\n",
    "import database\n",
    "database.init_db()\n",
    "print('Database configuration successfully seeded.')\n"
]

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": cell_3_lines
})

# ==========================================================
# CELL 4: Assessment Datasets (PHQ-9, GAD-7, WHO-5, PSS)
# ==========================================================
cell_4_lines = [
    "# Cell 4: Assessment Datasets\n",
    "# Set up the assessments metadata JSON files on disk\n",
    "import json\n",
    "import os\n",
    "\n",
    "assessments = {\n",
    "    'phq9': {\n",
    "        'name': 'PHQ-9 (Patient Health Questionnaire-9)',\n",
    "        'description': 'Measures severity of depression over the past 2 weeks.',\n",
    "        'questions': [\n",
    "            {'id': 'q1', 'text': 'Little interest or pleasure in doing things', 'options': ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], 'scores': [0, 1, 2, 3]},\n",
    "            {'id': 'q2', 'text': 'Feeling down, depressed, or hopeless', 'options': ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], 'scores': [0, 1, 2, 3]},\n",
    "            {'id': 'q3', 'text': 'Trouble falling or staying asleep, or sleeping too much', 'options': ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], 'scores': [0, 1, 2, 3]},\n",
    "            {'id': 'q4', 'text': 'Feeling tired or having little energy', 'options': ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], 'scores': [0, 1, 2, 3]},\n",
    "            {'id': 'q5', 'text': 'Poor appetite or overeating', 'options': ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], 'scores': [0, 1, 2, 3]},\n",
    "            {'id': 'q6', 'text': 'Feeling bad about yourself - or that you are a failure or have let yourself or your family down', 'options': ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], 'scores': [0, 1, 2, 3]},\n",
    "            {'id': 'q7', 'text': 'Trouble concentrating on things, such as reading the newspaper or watching television', 'options': ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], 'scores': [0, 1, 2, 3]},\n",
    "            {'id': 'q8', 'text': 'Moving or speaking so slowly that other people could have noticed? Or the opposite - being so fidgety or restless that you have been moving around a lot more than usual', 'options': ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], 'scores': [0, 1, 2, 3]},\n",
    "            {'id': 'q9', 'text': 'Thoughts that you would be better off dead or of hurting yourself in some way', 'options': ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], 'scores': [0, 1, 2, 3]}\n",
    "        ],\n",
    "        'scoring': {\n",
    "            'type': 'sum',\n",
    "            'brackets': [\n",
    "                {'min': 0, 'max': 4, 'severity': 'Minimal/None', 'risk': 'low'},\n",
    "                {'min': 5, 'max': 9, 'severity': 'Mild Depression', 'risk': 'low'},\n",
    "                {'min': 10, 'max': 14, 'severity': 'Moderate Depression', 'risk': 'medium'},\n",
    "                {'min': 15, 'max': 19, 'severity': 'Moderately Severe Depression', 'risk': 'medium'},\n",
    "                {'min': 20, 'max': 27, 'severity': 'Severe Depression', 'risk': 'high'}\n",
    "            ],\n",
    "            'risk_trigger': {'question_id': 'q9', 'threshold': 1, 'trigger_severity': 'high', 'message': 'Triggered suicidal ideation check on Q9.'}\n",
    "        }\n",
    "    },\n",
    "    'gad7': {\n",
    "        'name': 'GAD-7 (Generalized Anxiety Disorder-7)',\n",
    "        'description': 'Measures severity of generalized anxiety disorder.',\n",
    "        'questions': [\n",
    "            {'id': 'q1', 'text': 'Feeling nervous, anxious, or on edge', 'options': ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], 'scores': [0, 1, 2, 3]},\n",
    "            {'id': 'q2', 'text': 'Not being able to stop or control worrying', 'options': ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], 'scores': [0, 1, 2, 3]},\n",
    "            {'id': 'q3', 'text': 'Worrying too much about different things', 'options': ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], 'scores': [0, 1, 2, 3]},\n",
    "            {'id': 'q4', 'text': 'Trouble relaxing', 'options': ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], 'scores': [0, 1, 2, 3]},\n",
    "            {'id': 'q5', 'text': 'Being so restless that it is hard to sit still', 'options': ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], 'scores': [0, 1, 2, 3]},\n",
    "            {'id': 'q6', 'text': 'Becoming easily annoyed or irritable', 'options': ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], 'scores': [0, 1, 2, 3]},\n",
    "            {'id': 'q7', 'text': 'Feeling afraid as if something awful might happen', 'options': ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'], 'scores': [0, 1, 2, 3]}\n",
    "        ],\n",
    "        'scoring': {\n",
    "            'type': 'sum',\n",
    "            'brackets': [\n",
    "                {'min': 0, 'max': 4, 'severity': 'Minimal Anxiety', 'risk': 'low'},\n",
    "                {'min': 5, 'max': 9, 'severity': 'Mild Anxiety', 'risk': 'low'},\n",
    "                {'min': 10, 'max': 14, 'severity': 'Moderate Anxiety', 'risk': 'medium'},\n",
    "                {'min': 15, 'max': 21, 'severity': 'Severe Anxiety', 'risk': 'high'}\n",
    "            ]\n",
    "        }\n",
    "    },\n",
    "    'who5': {\n",
    "        'name': 'WHO-5 (Five Well-Being Index)',\n",
    "        'description': 'Measures subjective psychological well-being over the past two weeks.',\n",
    "        'questions': [\n",
    "            {'id': 'q1', 'text': 'I have felt cheerful and in good spirits', 'options': ['All of the time', 'Most of the time', 'More than half of the time', 'Less than half of the time', 'Some of the time', 'At no time'], 'scores': [5, 4, 3, 2, 1, 0]},\n",
    "            {'id': 'q2', 'text': 'I have felt calm and relaxed', 'options': ['All of the time', 'Most of the time', 'More than half of the time', 'Less than half of the time', 'Some of the time', 'At no time'], 'scores': [5, 4, 3, 2, 1, 0]},\n",
    "            {'id': 'q3', 'text': 'I have felt active and vigorous', 'options': ['All of the time', 'Most of the time', 'More than half of the time', 'Less than half of the time', 'Some of the time', 'At no time'], 'scores': [5, 4, 3, 2, 1, 0]},\n",
    "            {'id': 'q4', 'text': 'I woke up feeling fresh and rested', 'options': ['All of the time', 'Most of the time', 'More than half of the time', 'Less than half of the time', 'Some of the time', 'At no time'], 'scores': [5, 4, 3, 2, 1, 0]},\n",
    "            {'id': 'q5', 'text': 'My daily life has been filled with things that interest me', 'options': ['All of the time', 'Most of the time', 'More than half of the time', 'Less than half of the time', 'Some of the time', 'At no time'], 'scores': [5, 4, 3, 2, 1, 0]}\n",
    "        ],\n",
    "        'scoring': {\n",
    "            'type': 'percentage_who5',\n",
    "            'brackets': [\n",
    "                {'min': 50, 'max': 100, 'severity': 'Good Well-being', 'risk': 'low'},\n",
    "                {'min': 29, 'max': 49, 'severity': 'Moderately Low Well-being', 'risk': 'medium'},\n",
    "                {'min': 0, 'max': 28, 'severity': 'Poor Well-being (Screening recommended)', 'risk': 'high'}\n",
    "            ]\n",
    "        }\n",
    "    },\n",
    "    'pss10': {\n",
    "        'name': 'PSS-10 (Perceived Stress Scale)',\n",
    "        'description': 'Measures appraisal of life stress during the past month.',\n",
    "        'questions': [\n",
    "            {'id': 'q1', 'text': 'In the last month, how often have you been upset because of something that happened unexpectedly?', 'options': ['Never', 'Almost never', 'Sometimes', 'Fairly often', 'Very often'], 'scores': [0, 1, 2, 3, 4]},\n",
    "            {'id': 'q2', 'text': 'In the last month, how often have you felt that you were unable to control the important things in your life?', 'options': ['Never', 'Almost never', 'Sometimes', 'Fairly often', 'Very often'], 'scores': [0, 1, 2, 3, 4]},\n",
    "            {'id': 'q3', 'text': 'In the last month, how often have you felt nervous and stress?', 'options': ['Never', 'Almost never', 'Sometimes', 'Fairly often', 'Very often'], 'scores': [0, 1, 2, 3, 4]},\n",
    "            {'id': 'q4', 'text': 'In the last month, how often have you felt confident about your ability to handle your personal problems?', 'options': ['Never', 'Almost never', 'Sometimes', 'Fairly often', 'Very often'], 'scores': [4, 3, 2, 1, 0]},\n",
    "            {'id': 'q5', 'text': 'In the last month, how often have you felt that things were going your way?', 'options': ['Never', 'Almost never', 'Sometimes', 'Fairly often', 'Very often'], 'scores': [4, 3, 2, 1, 0]},\n",
    "            {'id': 'q6', 'text': 'In the last month, how often have you found that you could not cope with all the things that you had to do?', 'options': ['Never', 'Almost never', 'Sometimes', 'Fairly often', 'Very often'], 'scores': [0, 1, 2, 3, 4]},\n",
    "            {'id': 'q7', 'text': 'In the last month, how often have you been able to control irritations in your life?', 'options': ['Never', 'Almost never', 'Sometimes', 'Fairly often', 'Very often'], 'scores': [4, 3, 2, 1, 0]},\n",
    "            {'id': 'q8', 'text': 'In the last month, how often have you felt that you were on top of things?', 'options': ['Never', 'Almost never', 'Sometimes', 'Fairly often', 'Very often'], 'scores': [4, 3, 2, 1, 0]},\n",
    "            {'id': 'q9', 'text': 'In the last month, how often have you been angered because of things that were outside of your control?', 'options': ['Never', 'Almost never', 'Sometimes', 'Fairly often', 'Very often'], 'scores': [0, 1, 2, 3, 4]},\n",
    "            {'id': 'q10', 'text': 'In the last month, how often have you felt difficulties were piling up so high that you could not overcome them?', 'options': ['Never', 'Almost never', 'Sometimes', 'Fairly often', 'Very often'], 'scores': [0, 1, 2, 3, 4]}\n",
    "        ],\n",
    "        'scoring': {\n",
    "            'type': 'sum',\n",
    "            'brackets': [\n",
    "                {'min': 0, 'max': 13, 'severity': 'Low Stress', 'risk': 'low'},\n",
    "                {'min': 14, 'max': 26, 'severity': 'Moderate Stress', 'risk': 'low'},\n",
    "                {'min': 27, 'max': 40, 'severity': 'High Stress', 'risk': 'medium'}\n",
    "            ]\n",
    "        }\n",
    "    }\n",
    "}\n",
    "\n",
    "for key, val in assessments.items():\n",
    "    filepath = f'data/assessments/{key}.json'\n",
    "    with open(filepath, 'w', encoding='utf-8') as f:\n",
    "        json.dump(val, f, indent=4)\n",
    "    print(f'Generated JSON dataset for {key} at {filepath}')\n"

]

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": cell_4_lines
})

# ==========================================================
# CELL 5: Vector Database Creation (LangChain + FAISS + Incremental)
# ==========================================================
cell_5_lines = [
    "# Cell 5: Vector Database Creation\n",
    "# Create rag_assistant.py utilizing LangChain FAISS, HuggingFaceEmbeddings, and MD5 file hashes for incremental indexing\n",
    "\n",
    "with open('rag_assistant.py', 'w', encoding='utf-8') as f:\n",
    "    f.write('''import os\n",
    "import hashlib\n",
    "import json\n",
    "import pypdf\n",
    "from langchain_community.vectorstores import FAISS\n",
    "from langchain_huggingface import HuggingFaceEmbeddings\n",
    "from langchain_text_splitters import RecursiveCharacterTextSplitter\n",
    "\n",
    "class RAGAssistant:\n",
    "    def __init__(self, index_dir=\"data/faiss_index\", index_file=\"data/indexed_files.json\"):\n",
    "        self.index_dir = index_dir\n",
    "        self.index_file = index_file\n",
    "        self.embeddings = HuggingFaceEmbeddings(model_name=\"all-MiniLM-L6-v2\")\n",
    "        self.db = None\n",
    "        self.indexed_files = {}\n",
    "        self.load_indexed_files_tracker()\n",
    "        self.load_index()\n",
    "\n",
    "    def get_file_hash(self, filepath):\n",
    "        hasher = hashlib.md5()\n",
    "        with open(filepath, \\'rb\\') as f:\n",
    "            buf = f.read()\n",
    "            hasher.update(buf)\n",
    "        return hasher.hexdigest()\n",
    "\n",
    "    def load_indexed_files_tracker(self):\n",
    "        if os.path.exists(self.index_file):\n",
    "            try:\n",
    "                with open(self.index_file, \\'r\\', encoding=\\'utf-8\\') as f:\n",
    "                    self.indexed_files = json.load(f)\n",
    "            except Exception:\n",
    "                self.indexed_files = {}\n",
    "        else:\n",
    "            self.indexed_files = {}\n",
    "\n",
    "    def save_indexed_files_tracker(self):\n",
    "        os.makedirs(os.path.dirname(self.index_file), exist_ok=True)\n",
    "        with open(self.index_file, \\'w\\', encoding=\\'utf-8\\') as f:\n",
    "            json.dump(self.indexed_files, f, indent=4)\n",
    "\n",
    "    def load_index(self):\n",
    "        if os.path.exists(os.path.join(self.index_dir, \"index.faiss\")):\n",
    "            try:\n",
    "                self.db = FAISS.load_local(self.index_dir, self.embeddings, allow_dangerous_deserialization=True)\n",
    "                print(\"LangChain FAISS index loaded successfully.\")\n",
    "            except Exception as e:\n",
    "                print(f\"Error loading FAISS: {e}\")\n",
    "                self.db = None\n",
    "        else:\n",
    "            print(\"No FAISS index found. Ready for indexing.\")\n",
    "\n",
    "    def add_pdf(self, pdf_path):\n",
    "        filename = os.path.basename(pdf_path)\n",
    "        file_hash = self.get_file_hash(pdf_path)\n",
    "        \n",
    "        if filename in self.indexed_files and self.indexed_files[filename] == file_hash:\n",
    "            print(f\"File {filename} is already indexed. Skipping.\")\n",
    "            return 0\n",
    "            \n",
    "        pages = []\n",
    "        try:\n",
    "            reader = pypdf.PdfReader(pdf_path)\n",
    "            for i, page in enumerate(reader.pages):\n",
    "                text = page.extract_text()\n",
    "                if text and len(text.strip()) > 10:\n",
    "                    pages.append((text.strip(), i + 1))\n",
    "        except Exception as e:\n",
    "            print(f\"Error reading PDF: {e}\")\n",
    "            return 0\n",
    "            \n",
    "        if not pages:\n",
    "            return 0\n",
    "            \n",
    "        text_splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)\n",
    "        docs = []\n",
    "        for text, page_num in pages:\n",
    "            chunks = text_splitter.split_text(text)\n",
    "            for chunk in chunks:\n",
    "                if len(chunk.strip()) > 20:\n",
    "                    from langchain_core.documents import Document\n",
    "                    docs.append(Document(\n",
    "                        page_content=chunk,\n",
    "                        metadata={\"source\": filename, \"page\": page_num}\n",
    "                    ))\n",
    "                    \n",
    "        if not docs:\n",
    "            return 0\n",
    "            \n",
    "        if self.db is None:\n",
    "            self.db = FAISS.from_documents(docs, self.embeddings)\n",
    "        else:\n",
    "            self.db.add_documents(docs)\n",
    "            \n",
    "        self.db.save_local(self.index_dir)\n",
    "        self.indexed_files[filename] = file_hash\n",
    "        self.save_indexed_files_tracker()\n",
    "        return len(docs)\n",
    "\n",
    "    def search(self, query, top_k=3):\n",
    "        if self.db is None:\n",
    "            return []\n",
    "        try:\n",
    "            results = self.db.similarity_search_with_score(query, k=top_k)\n",
    "            matches = []\n",
    "            for doc, score in results:\n",
    "                matches.append({\n",
    "                    \"text\": doc.page_content,\n",
    "                    \"page\": doc.metadata.get(\"page\", 1),\n",
    "                    \"source\": doc.metadata.get(\"source\", \"Unknown\"),\n",
    "                    \"distance\": float(score)\n",
    "                })\n",
    "            return matches\n",
    "        except Exception:\n",
    "            return []\n",
    "''')\n",
    "print('rag_assistant.py successfully generated.')\n"
]

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": cell_5_lines
})

# ==========================================================
# CELL 6: Prompt Templates setup
# ==========================================================
cell_6_lines = [
    "# Cell 6: Prompt Templates Folder Setup\n",
    "# Create prompts/ directory and write 5 configurable prompt text files\n",
    "import os\n",
    "\n",
    "os.makedirs('prompts', exist_ok=True)\n",
    "\n",
    "prompts_dict = {\n",
    "    'intake_prompt.txt': (\n",
    "        'You are a welcoming intake coordinator for CareMinds AI.\\\\n'\n",
    "        'Empathetically collect patient demographics: Full Name, DOB, Gender, Phone, and Consent.\\\\n'\n",
    "        'Assure data privacy and compliance guidelines.'\n",
    "    ),\n",
    "    'assessment_prompt.txt': (\n",
    "        'You are a clinical facilitator presenting: {scale_name}.\\\\n'\n",
    "        'Description: {scale_description}\\\\n'\n",
    "        'Current Question: {question_text}\\\\n'\n",
    "        'Direct Options: {options}\\\\n\\\\n'\n",
    "        'Ask the question clearly and prompt the patient for answers.'\n",
    "    ),\n",
    "    'rag_prompt.txt': (\n",
    "        'You are a clinical database search agent.\\\\n'\n",
    "        'Answer ONLY using retrieved details. Cite the Doc and Page.\\\\n'\n",
    "        'If details are missing, say: \"I do not have this information in my documents. Please consult a qualified clinician.\"\\\\n\\\\n'\n",
    "        'Retrieved Context:\\\\n{context}\\\\n\\\\nQuery: {query}'\n",
    "    ),\n",
    "    'safety_prompt.txt': (\n",
    "        'Screen the patient input for suicidal ideation, intent, or self-harm triggers.\\\\n'\n",
    "        'Patient Input: \"{patient_input}\"\\\\n\\\\n'\n",
    "        'Return strictly JSON with keys: \"safety_trigger\" (bool), \"trigger_category\" (str), '\n",
    "        '\"risk_level\" (\"low\"|\"medium\"|\"high\"), \"action_required\" (bool), \"recommended_response\" (str).'\n",
    "    ),\n",
    "    'report_prompt.txt': (\n",
    "        'Write a professional SOAP note summary for the assessment: {assessment_name}.\\\\n'\n",
    "        'Patient Name: {patient_name} | DOB: {dob} | Gender: {gender}\\\\n'\n",
    "        'Instrument Score: {score} | Severity: {severity} | Safety Risk: {risk_level}\\\\n\\\\n'\n",
    "        'Patient Answers Table:\\\\n{responses_table}\\\\n\\\\n'\n",
    "        'Format output under Markdown headings: 1. Subjective, 2. Objective, 3. Assessment, 4. Plan.'\n",
    "    )\n",
    "}\n",
    "\n",
    "for filename, content in prompts_dict.items():\n",
    "    filepath = f'prompts/{filename}'\n",
    "    with open(filepath, 'w', encoding='utf-8') as f:\n",
    "        f.write(content)\n",
    "    print(f'Created prompt template file: {filepath}')\n"

]

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": cell_6_lines
})

# ==========================================================
# CELL 7: Agent Implementations
# ==========================================================
cell_7_lines = [
    "# Cell 7: Agent Implementations\n",
    "# Create agents.py with configurable prompt loadings from folder, safety triggers and SOAP generator\n",
    "\n",
    "with open('agents.py', 'w', encoding='utf-8') as f:\n",
    "    f.write('''import json\n",
    "import re\n",
    "import os\n",
    "import sqlite3\n",
    "from groq import Groq\n",
    "import config\n",
    "import database\n",
    "\n",
    "def load_prompt_file(filename, fallback):\n",
    "    path = os.path.join(\"prompts\", filename)\n",
    "    if os.path.exists(path):\n",
    "        with open(path, \"r\", encoding=\"utf-8\") as f:\n",
    "            return f.read()\n",
    "    return fallback\n",
    "\n",
    "def parse_gemini_json(text):\n",
    "    text = text.strip()\n",
    "    match = re.search(r\"```json\\\\s*(.*?)\\\\s*```\", text, re.DOTALL)\n",
    "    if match:\n",
    "        json_str = match.group(1)\n",
    "    else:\n",
    "        match = re.search(r\"```\\\\s*(.*?)\\\\s*```\", text, re.DOTALL)\n",
    "        if match:\n",
    "            json_str = match.group(1)\n",
    "        else:\n",
    "            json_str = text\n",
    "    try:\n",
    "        return json.loads(json_str)\n",
    "    except Exception:\n",
    "        try:\n",
    "            match = re.search(r\"(\\\\{.*\\\\}|\\\\[.*\\\\])\", json_str, re.DOTALL)\n",
    "            if match:\n",
    "                return json.loads(match.group(1))\n",
    "        except:\n",
    "            pass\n",
    "        return {}\n",
    "\n",
    "class GroqClient:\n",
    "    def __init__(self):\n",
    "        self.api_key = config.GROQ_API_KEY\n",
    "        if not self.api_key:\n",
    "            self.api_key = os.environ.get(\"GROQ_API_KEY\", \"\")\n",
    "        self.client = None\n",
    "        self.model_name = \"llama-3.3-70b-versatile\"\n",
    "        if self.api_key:\n",
    "            try:\n",
    "                self.client = Groq(api_key=self.api_key)\n",
    "            except Exception as e:\n",
    "                print(f\"Failed to initialize Groq Client: {e}\")\n",
    "\n",
    "    def generate(self, prompt, system_instruction=None):\n",
    "        if not self.client:\n",
    "            self.api_key = config.GROQ_API_KEY or os.environ.get(\"GROQ_API_KEY\", \"\")\n",
    "            if self.api_key:\n",
    "                try:\n",
    "                    self.client = Groq(api_key=self.api_key)\n",
    "                except Exception as e:\n",
    "                    return f\"Groq API Key initialization error: {str(e)}\"\n",
    "            else:\n",
    "                return \"Groq API Key is not set. Running in local fallback mode.\"\n",
    "        \n",
    "        try:\n",
    "            messages = []\n",
    "            if system_instruction:\n",
    "                messages.append({\"role\": \"system\", \"content\": system_instruction})\n",
    "            messages.append({\"role\": \"user\", \"content\": prompt})\n",
    "            \n",
    "            chat_completion = self.client.chat.completions.create(\n",
    "                messages=messages,\n",
    "                model=self.model_name,\n",
    "            )\n",
    "            return chat_completion.choices[0].message.content\n",
    "        except Exception as e:\n",
    "            return f\"Groq Error: {str(e)}\"\n",
    "\n",
    "gemini_client = GroqClient()\n",
    "\n",
    "class SecurityManager:\n",
    "    @staticmethod\n",
    "    def hash_password(password):\n",
    "        import hashlib\n",
    "        return hashlib.sha256(password.encode()).hexdigest()\n",
    "\n",
    "    @staticmethod\n",
    "    def verify_password(password, hashed):\n",
    "        return SecurityManager.hash_password(password) == hashed\n",
    "\n",
    "    @staticmethod\n",
    "    def register_user(username, password, role, full_name, email):\n",
    "        conn = database.get_connection()\n",
    "        cursor = conn.cursor()\n",
    "        password_hash = SecurityManager.hash_password(password)\n",
    "        try:\n",
    "            cursor.execute(\"\"\"\n",
    "            INSERT INTO users (username, password_hash, role, full_name, email)\n",
    "            VALUES (?, ?, ?, ?, ?)\n",
    "            \"\"\", (username, password_hash, role, full_name, email))\n",
    "            user_id = cursor.lastrowid\n",
    "            if role == config.ROLE_PATIENT:\n",
    "                cursor.execute(\"\"\"\n",
    "                INSERT INTO patients (user_id, dob, age, gender, phone, consent_given, assigned_psychologist_id)\n",
    "                VALUES (?, \\'\\', 30, \\'\\', \\'\\', 0, 2)\n",
    "                \"\"\", (user_id,))\n",
    "            conn.commit()\n",
    "            database.log_audit(user_id, \"user_registration\", \"users\", user_id)\n",
    "            return user_id, None\n",
    "        except sqlite3.IntegrityError:\n",
    "            return None, \"Username already exists.\"\n",
    "        finally:\n",
    "            conn.close()\n",
    "\n",
    "    @staticmethod\n",
    "    def authenticate_user(username, password):\n",
    "        conn = database.get_connection()\n",
    "        cursor = conn.cursor()\n",
    "        cursor.execute(\"SELECT * FROM users WHERE username = ?\", (username,))\n",
    "        user = cursor.fetchone()\n",
    "        conn.close()\n",
    "        if user and SecurityManager.verify_password(password, user[\\'password_hash\\']):\n",
    "            database.log_audit(user[\\'id\\'], \"user_login\", \"users\", user[\\'id\\'])\n",
    "            return dict(user)\n",
    "        return None\n",
    "\n",
    "    @staticmethod\n",
    "    def update_patient_profile(user_id, dob, gender, phone, consent_given):\n",
    "        from datetime import datetime\n",
    "        conn = database.get_connection()\n",
    "        cursor = conn.cursor()\n",
    "        cursor.execute(\"SELECT id FROM users WHERE id = ?\", (user_id,))\n",
    "        if not cursor.fetchone():\n",
    "            conn.close()\n",
    "            return False, \"User not found.\"\n",
    "        cursor.execute(\"SELECT id FROM patients WHERE user_id = ?\", (user_id,))\n",
    "        patient = cursor.fetchone()\n",
    "        consent_date = datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\") if consent_given else None\n",
    "        \n",
    "        # Calculate approximate age\n",
    "        age = 30\n",
    "        try:\n",
    "            birth_year = int(dob.split(\"-\")[0])\n",
    "            age = datetime.now().year - birth_year\n",
    "        except:\n",
    "            pass\n",
    "            \n",
    "        if patient:\n",
    "            cursor.execute(\"\"\"\n",
    "            UPDATE patients\n",
    "            SET dob = ?, age = ?, gender = ?, phone = ?, consent_given = ?, consent_date = ?\n",
    "            WHERE user_id = ?\n",
    "            \"\"\", (dob, age, gender, phone, int(consent_given), consent_date, user_id))\n",
    "            patient_id = patient[\\'id\\']\n",
    "        else:\n",
    "            cursor.execute(\"\"\"\n",
    "            INSERT INTO patients (user_id, dob, age, gender, phone, consent_given, consent_date, assigned_psychologist_id)\n",
    "            VALUES (?, ?, ?, ?, ?, ?, ?, 2)\n",
    "            \"\"\", (user_id, dob, age, gender, phone, int(consent_given), consent_date))\n",
    "            patient_id = cursor.lastrowid\n",
    "        conn.commit()\n",
    "        database.log_audit(user_id, \"update_patient_profile\", \"patients\", patient_id)\n",
    "        conn.close()\n",
    "        return True, \"Profile saved.\"\n",
    "\n",
    "    @staticmethod\n",
    "    def get_patient_profile(user_id):\n",
    "        conn = database.get_connection()\n",
    "        cursor = conn.cursor()\n",
    "        cursor.execute(\"\"\"\n",
    "        SELECT u.id as user_id, u.username, u.full_name, u.email, u.role,\n",
    "               p.id as patient_id, p.dob, p.age, p.gender, p.phone, p.consent_given, p.consent_date, p.assigned_psychologist_id\n",
    "        FROM users u\n",
    "        LEFT JOIN patients p ON u.id = p.user_id\n",
    "        WHERE u.id = ?\n",
    "        \"\"\", (user_id,))\n",
    "        row = cursor.fetchone()\n",
    "        conn.close()\n",
    "        return dict(row) if row else None\n",
    "\n",
    "class SafetyAgent:\n",
    "    @staticmethod\n",
    "    def check_safety(patient_input):\n",
    "        fallback = \\\"\\\"\\\"Analyze for suicide or self harm risk. Return strictly JSON with safety_trigger key.\\\"\\\"\\\"\n",
    "        instructions = load_prompt_file(\"safety_prompt.txt\", fallback)\n",
    "        prompt = instructions.format(patient_input=patient_input)\n",
    "        raw_output = gemini_client.generate(prompt, \"Check crisis flags. Output JSON.\")\n",
    "        \n",
    "        if not gemini_client.model_name or \"Gemini API Key\" in raw_output:\n",
    "            triggers = [\"suicide\", \"kill myself\", \"want to die\", \"harm myself\", \"end my life\", \"cut myself\", \"overdose\", \"hang myself\"]\n",
    "            triggered = any(t in patient_input.lower() for t in triggers)\n",
    "            return {\n",
    "                \"safety_trigger\": triggered,\n",
    "                \"trigger_category\": \"suicidal_ideation\" if triggered else \"none\",\n",
    "                \"risk_level\": \"high\" if triggered else \"low\",\n",
    "                \"action_required\": triggered,\n",
    "                \"recommended_response\": \"WARNING: Safety concern identified. Please consult a qualified mental health professional or immediately contact the Suicide & Crisis Lifeline by dialing 988. You do not have to carry this alone.\"\n",
    "            }\n",
    "        return parse_gemini_json(raw_output)\n",
    "\n",
    "class ScoringEngine:\n",
    "    @staticmethod\n",
    "    def score_session(session_id, scale_data):\n",
    "        conn = database.get_connection()\n",
    "        cursor = conn.cursor()\n",
    "        cursor.execute(\"SELECT question_id, response_value FROM assessment_responses WHERE session_id = ?;\", (session_id,))\n",
    "        rows = cursor.fetchall()\n",
    "        conn.close()\n",
    "        responses = {r[\"question_id\"]: r[\"response_value\"] for r in rows}\n",
    "        scoring_type = scale_data[\"scoring\"][\"type\"]\n",
    "        total_score = 0\n",
    "        if scoring_type == \"sum\":\n",
    "            total_score = sum(responses.values())\n",
    "        elif scoring_type == \"percentage_who5\":\n",
    "            total_score = sum(responses.values()) * 4\n",
    "            \n",
    "        severity = \"Unknown\"\n",
    "        risk_level = \"low\"\n",
    "        for b in scale_data[\"scoring\"][\"brackets\"]:\n",
    "            if b[\"min\"] <= total_score <= b[\"max\"]:\n",
    "                severity = b[\"severity\"]\n",
    "                risk_level = b[\"risk\"]\n",
    "                break\n",
    "        risk_trigger = scale_data[\"scoring\"].get(\"risk_trigger\")\n",
    "        if risk_trigger:\n",
    "            trigger_qid = risk_trigger[\"question_id\"]\n",
    "            if trigger_qid in responses and responses[trigger_qid] >= risk_trigger[\"threshold\"]:\n",
    "                risk_level = risk_trigger[\"trigger_severity\"]\n",
    "        return total_score, severity, risk_level\n",
    "\n",
    "class AssessmentAgent:\n",
    "    @staticmethod\n",
    "    def map_user_response(user_text, options, scores):\n",
    "        # 1. Local matching first (handles direct button clicks & exact option typing immediately)\n",
    r"        user_clean = re.sub(r'[^\\w\\s]', '', user_text).strip().lower()\n",
    "        for idx, opt in enumerate(options):\n",
    r"            opt_clean = re.sub(r'[^\\w\\s]', '', opt).strip().lower()\n",
    "            if user_clean == opt_clean:\n",
    "                return {\"matched_index\": idx}\n",
    "        for idx in range(len(options)):\n",
    "            if user_clean == str(idx):\n",
    "                return {\"matched_index\": idx}\n",
    "\n",
    "        # 2. Call Gemini for conversational mapping\n",
    "        options_str = \"\\\\n\".join([f\"- {idx}: {opt}\" for idx, opt in enumerate(options)])\n",
    "        fallback = \\\"\\\"\\\"Map user response to option index. Return JSON: {\\\\\"matched_index\\\\\": int}\\\"\\\"\\\"\n",
    "        instructions = load_prompt_file(\"assessment_prompt.txt\", fallback)\n",
    "        prompt = f\\'{instructions}\\\\nMap User Response: \\\"{user_text}\\\" to options:\\\\n{options_str}\\'\\n",
    "        raw_output = gemini_client.generate(prompt, \"Map choices. Output JSON.\")\n",
    "        \n",
    "        # If client is not set or Gemini returned an error, fallback to local search\n",
    "        if not gemini_client.model_name or \"Gemini API Key\" in raw_output or \"Gemini Error\" in raw_output:\n",
    "            for idx, opt in enumerate(options):\n",
    r"                opt_clean = re.sub(r'[^\\w\\s]', '', opt).strip().lower()\n",
    "                if opt_clean in user_clean:\n",
    "                    return {\"matched_index\": idx}\n",
    "            for i in range(len(options)):\n",
    "                if str(i) in user_clean:\n",
    "                    return {\"matched_index\": i}\n",
    "            return {\"matched_index\": -1}\n",
    "            \n",
    "        parsed = parse_gemini_json(raw_output)\n",
    "        if \"matched_index\" in parsed and isinstance(parsed[\"matched_index\"], int) and 0 <= parsed[\"matched_index\"] < len(options):\n",
    "            return parsed\n",
    "            \n",
    "        # Fallback if parsed json is invalid or missing matched_index\n",
    "        for idx, opt in enumerate(options):\n",
    r"            opt_clean = re.sub(r'[^\\w\\s]', '', opt).strip().lower()\n",
    "            if opt_clean in user_clean:\n",
    "                return {\"matched_index\": idx}\n",
    "        for i in range(len(options)):\n",
    "            if str(i) in user_clean:\n",
    "                return {\"matched_index\": i}\n",
    "        return {\"matched_index\": -1}\n",
    "\n",
    "class SessionSummarizerAgent:\n",
    "    @staticmethod\n",
    "    def generate_clinical_notes(session_id):\n",
    "        conn = database.get_connection()\n",
    "        cursor = conn.cursor()\n",
    "        cursor.execute(\"\"\"\n",
    "        SELECT s.assessment_name, s.score, s.severity, s.risk_level,\n",
    "               p.dob, p.gender, u.full_name as patient_name\n",
    "        FROM assessment_sessions s\n",
    "        JOIN patients p ON s.patient_id = p.id\n",
    "        JOIN users u ON p.user_id = u.id\n",
    "        WHERE s.id = ?\n",
    "        \"\"\", (session_id,))\n",
    "        session = cursor.fetchone()\n",
    "        if not session:\n",
    "            conn.close()\n",
    "            return\n",
    "        cursor.execute(\"SELECT question_id, response_text, response_value FROM assessment_responses WHERE session_id = ?;\", (session_id,))\n",
    "        responses = cursor.fetchall()\n",
    "        conn.close()\n",
    "        resp_table = \"\"\n",
    "        for r in responses:\n",
    "            resp_table += f\"- Q {r[\\'question_id\\']}: {r[\\'response_text\\']} (Weight: {r[\\'response_value\\']})\\\\n\"\n",
    "        \n",
    "        fallback = \\\"\\\"\\\"Write SOAP notes. Format with headers Subjective, Objective, Assessment, Plan.\\\"\\\"\\\"\n",
    "        instructions = load_prompt_file(\"report_prompt.txt\", fallback)\n",
    "        prompt = instructions.format(\n",
    "            assessment_name=session[\"assessment_name\"],\n",
    "            patient_name=session[\"patient_name\"],\n",
    "            dob=session[\"dob\"],\n",
    "            gender=session[\"gender\"],\n",
    "            score=session[\"score\"],\n",
    "            severity=session[\"severity\"],\n",
    "            risk_level=session[\"risk_level\"],\n",
    "            responses_table=resp_table\n",
    "        )\n",
    "        soap_notes = gemini_client.generate(prompt, \"Draft SOAP clinical notes.\")\n",
    "        summary_text = f\"Completed assessment {session[\\'assessment_name\\']}. Score: {session[\\'score\\']}.\"\n",
    "        \n",
    "        action_items = \"Follow clinical recommendations.\"\n",
    "        action_split = soap_notes.lower().split(\"plan**\")\n",
    "        if len(action_split) > 1:\n",
    "            action_items = action_split[1].replace(\"**\", \"\").strip()\n",
    "            \n",
    "        conn = database.get_connection()\n",
    "        cursor = conn.cursor()\n",
    "        cursor.execute(\"\"\"\n",
    "        INSERT OR REPLACE INTO session_summaries (session_id, summary_text, clinician_notes, action_items)\n",
    "        VALUES (?, ?, ?, ?)\n",
    "        \"\"\", (session_id, summary_text, soap_notes, action_items))\n",
    "        conn.commit()\n",
    "        conn.close()\n",
    "        return summary_text, soap_notes, action_items\n",
    "''')\n",
    "print('agents.py successfully generated.')\n"
]

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": cell_7_lines
})

# ==========================================================
# CELL 8: Streamlit Interface Setup (part 1)
# ==========================================================
cell_8_source_lines = [
    "# Cell 8: Streamlit Main Interface App\n",
    "# Writes the entire Streamlit portal UI logic (app.py) directly\n",
    "\n",
    "with open('app.py', 'w', encoding='utf-8') as f:\n",
    "    f.write('''import streamlit as st\n",
    "import os\n",
    "import json\n",
    "from datetime import datetime\n",
    "import plotly.graph_objects as go\n",
    "import plotly.express as px\n",
    "\n",
    "import config\n",
    "import database\n",
    "import agents\n",
    "import report_generator\n",
    "from rag_assistant import RAGAssistant\n",
    "\n",
    "st.set_page_config(page_title=\"CareMinds AI Platform\", page_icon=\"🧠\", layout=\"wide\")\n",
    "\n",
    "st.markdown(\"\"\"\n",
    "<style>\n",
    "    .stApp { background-color: #0A0D16; color: #F1F5F9; }\n",
    "    div.stButton > button { background-color: #2563EB; color: white; border-radius: 6px; }\n",
    "    .metric-card { background: #1E293B; border-radius: 8px; padding: 1.2rem; margin-bottom: 0.8rem; border: 1px solid #334155; }\n",
    "    .crisis-card { background: #451A1A; border: 1.5px solid #EF4444; border-radius: 8px; padding: 1.2rem; color: #F87171; }\n",
    "    .alert-header { background: #7F1D1D; color: white; padding: 10px; border-radius: 6px; border: 1px solid #F87171; font-weight: bold; margin-bottom: 15px; }\n",
    "</style>\n",
    "\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "if \"rag\" not in st.session_state:\n",
    "    st.session_state.rag = RAGAssistant()\n",
    "if \"logged_in\" not in st.session_state:\n",
    "    st.session_state.logged_in = False\n",
    "if \"user\" not in st.session_state:\n",
    "    st.session_state.user = None\n",
    "if \"assessment_state\" not in st.session_state:\n",
    "    st.session_state.assessment_state = {\n",
    "        \"active\": False, \"scale_key\": None, \"q_idx\": 0, \"session_id\": None, \"answers\": {}, \"questions\": [], \"scale_data\": None\n",
    "    }\n",
    "\n",
    "# Session Memory helper\n",
    "def save_chat(session_id, sender, msg):\n",
    "    try:\n",
    "        conn = database.get_connection()\n",
    "        cursor = conn.cursor()\n",
    "        cursor.execute(\"INSERT INTO chat_messages (session_id, sender, message) VALUES (?, ?, ?)\",\n",
    "                       (session_id, sender, msg))\n",
    "        conn.commit()\n",
    "        conn.close()\n",
    "    except:\n",
    "        pass\n",
    "\n",
    "    # Voice support features removed\n",
    "def render_auth():\n",
    "    st.title(\"🧠 CareMinds AI Platform\")\n",
    "    st.subheader(\"Mental Health Assessment & Clinical Psychometric Portal\")\n",
    "    auth_mode = st.radio(\"Session Select\", [\"Login\", \"Sign Up\"], horizontal=True)\n",
    "    username = st.text_input(\"Username\")\n",
    "    password = st.text_input(\"Password\", type=\"password\")\n",
    "    if auth_mode == \"Login\":\n",
    "        if st.button(\"Access Platform\"):\n",
    "            user = agents.SecurityManager.authenticate_user(username, password)\n",
    "            if user:\n",
    "                st.session_state.logged_in = True\n",
    "                st.session_state.user = user\n",
    "                st.rerun()\n",
    "            else:\n",
    "                st.error(\"Incorrect credentials.\")\n",
    "    else:\n",
    "        full_name = st.text_input(\"Full Name\")\n",
    "        email = st.text_input(\"Email\")\n",
    "        role = st.selectbox(\"Role\", [config.ROLE_PATIENT, config.ROLE_PSYCHOLOGIST])\n",
    "        if st.button(\"Create User Profile\"):\n",
    "            uid, err = agents.SecurityManager.register_user(username, password, role, full_name, email)\n",
    "            if err: st.error(err)\n",
    "            else: st.success(\"Registered. Please login.\")\n",
    "\n",
    "def render_sidebar():\n",
    "    st.sidebar.title(\"CareMinds Workspace\")\n",
    "    st.sidebar.write(f\"User: **{st.session_state.user[\\'full_name\\']}**\")\n",
    "    st.sidebar.write(f\"Role: `{st.session_state.user[\\'role\\'].upper()}`\")\n",
    "    if st.sidebar.button(\"Log Out\"):\n",
    "        st.session_state.logged_in = False\n",
    "        st.session_state.user = None\n",
    "        st.session_state.assessment_state[\"active\"] = False\n",
    "        st.rerun()\n",
    "    st.sidebar.divider()\n",
    "    role = st.session_state.user[\"role\"]\n",
    "    if role == config.ROLE_PATIENT:\n",
    "        return st.sidebar.radio(\"Menu\", [\"Intake & Consent\", \"Assessment Center\", \"RAG Reference Help\", \"My Progress\"])\n",
    "    elif role == config.ROLE_PSYCHOLOGIST:\n",
    "        return st.sidebar.radio(\"Menu\", [\"Patient Dashboard\", \"RAG Reference Assistant\", \"Resource Administrator\"])\n",
    "    return st.sidebar.radio(\"Menu\", [\"Database Auditor\", \"Resource Administrator\"])\n",
    "\n",
    "def render_intake():\n",
    "    st.title(\"📋 Intake Information & Evaluation Consent\")\n",
    "    uid = st.session_state.user[\"id\"]\n",
    "    profile = agents.SecurityManager.get_patient_profile(uid)\n",
    "    dob = st.text_input(\"Date of Birth (YYYY-MM-DD)\", value=profile.get(\"dob\", \"\"))\n",
    "    gender = st.selectbox(\"Gender\", [\"Male\", \"Female\", \"Non-binary\", \"Undisclosed\"], index=0)\n",
    "    phone = st.text_input(\"Phone Number\", value=profile.get(\"phone\", \"\"))\n",
    "    st.subheader(\"Psychometric Informed Consent Agreement\")\n",
    "    st.caption(\"Your answers are evaluated deterministically to assess mood severity metrics. This AI is not a definitive diagnosis. High risk responses trigger crisis resource notifications.\")\n",
    "    consent = st.checkbox(\"I grant explicit consent for storing and scoring my responses.\", value=bool(profile.get(\"consent_given\", 0)))\n",
    "    if st.button(\"Update Patient Profile\"):\n",
    "        success, msg = agents.SecurityManager.update_patient_profile(uid, dob, gender, phone, consent)\n",
    "        if success: st.success(\"Profile successfully updated.\")\n",
    "        else: st.error(msg)\n",
    "\n",
    "def render_assessments():\n",
    "    st.title(\"📋 Conversational Screening Center\")\n",
    "    if st.session_state.get(\"crisis_detected\", False):\n",
    "        st.markdown(f\\'<div class=\"crisis-card\"><h3>⚠️ Crisis Resource Active</h3><p>{st.session_state.crisis_msg}</p></div>\\', unsafe_allow_html=True)\n",
    "        if st.button(\"I acknowledge this warning\"):\n",
    "            st.session_state.crisis_detected = False\n",
    "            st.session_state.assessment_state[\"active\"] = False\n",
    "            st.rerun()\n",
    "        return\n",
    "    \n",
    "    state = st.session_state.assessment_state\n",
    "    if not state[\"active\"]:\n",
    "        st.subheader(\"Choose clinical scale to start:\")\n",
    "        cols = st.columns(2)\n",
    "        with cols[0]:\n",
    "            if st.button(\"Start PHQ-9 Depression evaluation\"):\n",
    "                start_assessment(\"phq9\")\n",
    "            if st.button(\"Start WHO-5 Well-being evaluation\"):\n",
    "                start_assessment(\"who5\")\n",
    "        with cols[1]:\n",
    "            if st.button(\"Start GAD-7 Anxiety evaluation\"):\n",
    "                start_assessment(\"gad7\")\n",
    "            if st.button(\"Start PSS-10 Stress evaluation\"):\n",
    "                start_assessment(\"pss10\")\n",
    "    else:\n",
    "        run_active_assessment()\n",
    "\n",
    "def start_assessment(key):\n",
    "    profile = agents.SecurityManager.get_patient_profile(st.session_state.user[\"id\"])\n",
    "    if not profile or not profile.get(\"consent_given\", 0):\n",
    "        st.error(\"You must fill in details and grant consent in \\'Intake & Consent\\' tab first.\")\n",
    "        return\n",
    "    filepath = f\"data/assessments/{key}.json\"\n",
    "    with open(filepath, \"r\", encoding=\"utf-8\") as f: data = json.load(f)\n",
    "    conn = database.get_connection()\n",
    "    cursor = conn.cursor()\n",
    "    cursor.execute(\"\"\"\n",
    "    INSERT INTO assessment_sessions (patient_id, assessment_name, status, started_at)\n",
    "    VALUES (?, ?, \\'started\\', ?)\n",
    "    \"\"\", (profile[\"patient_id\"], data[\"name\"], datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")))\n",
    "    sid = cursor.lastrowid\n",
    "    conn.commit()\n",
    "    conn.close()\n",
    "    st.session_state.assessment_state = {\n",
    "        \"active\": True, \"scale_key\": key, \"q_idx\": 0, \"session_id\": sid, \"answers\": {}, \"questions\": data[\"questions\"], \"scale_data\": data\n",
    "    }\n",
    "    database.log_audit(st.session_state.user[\"id\"], f\"started_assessment_{key}\", \"assessment_sessions\", sid)\n",
    "    st.rerun()\n",
    "\n",
    "def run_active_assessment():\n",
    "    state = st.session_state.assessment_state\n",
    "    questions = state[\"questions\"]\n",
    "    q_idx = state[\"q_idx\"]\n",
    "    \n",
    "    if q_idx >= len(questions):\n",
    "        score, severity, risk = agents.ScoringEngine.score_session(state[\"session_id\"], state[\"scale_data\"])\n",
    "        conn = database.get_connection()\n",
    "        cursor = conn.cursor()\n",
    "        cursor.execute(\"\"\"\n",
    "        UPDATE assessment_sessions\n",
    "        SET status = \\'completed\\', score = ?, severity = ?, risk_level = ?, completed_at = ?\n",
    "        WHERE id = ?\n",
    "        \"\"\", (score, severity, risk, datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\"), state[\"session_id\"]))\n",
    "        conn.commit()\n",
    "        conn.close()\n",
    "        \n",
    "        database.log_audit(st.session_state.user[\"id\"], f\"completed_{state[\\'scale_key\\']}\", \"assessment_sessions\", state[\"session_id\"])\n",
    "        \n",
    "        with st.spinner(\"Creating clinical documentation SOAP file...\"):\n",
    "            summary_text, soap_notes, action_items = agents.SessionSummarizerAgent.generate_clinical_notes(state[\"session_id\"])\n",
    "            report_generator.ReportGenerator.generate_assessment_report(state[\"session_id\"])\n",
    "            \n",
    "        st.success(\"Screening completed!\")\n",
    "        st.metric(\"Calculated Instrument Score\", score)\n",
    "        st.write(f\"Classification Severity: **{severity}**\")\n",
    "        st.write(f\"Safety Flag Risk: **{risk.upper()}**\")\n",
    "        \n",
    "        # PDF Report Button\n",
    "        pdf_file = f\"reports/session_{state[\\'session_id\\']}_report.pdf\"\n",
    "        if os.path.exists(pdf_file):\n",
    "            with open(pdf_file, \"rb\") as f:\n",
    "                st.download_button(\"📥 Download Clinical Report PDF\", f, file_name=f\"report_{state[\\'session_id\\']}.pdf\", mime=\"application/pdf\")\n",
    "                \n",
    "        # JSON Report Button\n",
    "        profile = agents.SecurityManager.get_patient_profile(st.session_state.user[\"id\"])\n",
    "        json_report = {\n",
    "            \"session_id\": state[\"session_id\"],\n",
    "            \"patient_name\": profile[\"full_name\"],\n",
    "            \"dob\": profile[\"dob\"],\n",
    "            \"age\": profile[\"age\"],\n",
    "            \"gender\": profile[\"gender\"],\n",
    "            \"assessment\": state[\"scale_data\"][\"name\"],\n",
    "            \"score\": score,\n",
    "            \"severity\": severity,\n",
    "            \"risk_level\": risk,\n",
    "            \"completed_at\": datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\"),\n",
    "            \"SOAP_clinical_note\": soap_notes,\n",
    "            \"action_items\": action_items\n",
    "        }\n",
    "        st.download_button(\"📥 Export JSON Clinical Data\", json.dumps(json_report, indent=4), file_name=f\"report_{state[\\'session_id\\']}.json\", mime=\"application/json\")\n",
    "        \n",
    "        if st.button(\"Finish Session\"):\n",
    "            state[\"active\"] = False\n",
    "            st.rerun()\n",
    "        return\n",
    "    \n",
    "    q = questions[q_idx]\n",
    "    st.subheader(f\"Question {q_idx+1} of {len(questions)}:\")\n",
    "    st.info(q[\"text\"])\n",
    "    \n",
    "    # Fetch chat memory messages for this session\n",
    "    conn = database.get_connection()\n",
    "    cursor = conn.cursor()\n",
    "    cursor.execute(\"SELECT sender, message FROM chat_messages WHERE session_id = ? ORDER BY id ASC\", (state[\"session_id\"],))\n",
    "    messages = cursor.fetchall()\n",
    "    conn.close()\n",
    "    \n",
    "    for m in messages:\n",
    "        with st.chat_message(\"user\" if m[0] == \"user\" else \"assistant\"):\n",
    "            st.write(m[1])\n",
    "            \n",
    "    text_ans = st.text_input(\"Your reply: (or select an option below)\", key=f\"ans_{q_idx}\")\n",
    "    opt_cols = st.columns(len(q[\"options\"]))\n",
    "    clicked = None\n",
    "    for i, opt in enumerate(q[\"options\"]):\n",
    "        if opt_cols[i].button(opt, key=f\"btn_{q_idx}_{i}\"):\n",
    "            clicked = opt\n",
    "            \n",
    "    final_ans = clicked if clicked else text_ans\n",
    "    if st.button(\"Submit Response\", key=f\"sub_{q_idx}\") or clicked:\n",
    "        if not final_ans: st.warning(\"Please write or select an answer.\")\n",
    "        else:\n",
    "            # Session Memory log user reply\n",
    "            save_chat(state[\"session_id\"], \"user\", final_ans)\n",
    "            \n",
    "            safety = agents.SafetyAgent.check_safety(final_ans)\n",
    "            if safety.get(\"safety_trigger\", False):\n",
    "                st.session_state.crisis_detected = True\n",
    "                st.session_state.crisis_msg = safety.get(\"recommended_response\")\n",
    "                \n",
    "                conn = database.get_connection()\n",
    "                cursor = conn.cursor()\n",
    "                cursor.execute(\"\"\"\n",
    "                UPDATE assessment_sessions \n",
    "                SET status = \\'completed\\', score = 0, severity = \\'Crisis Distress\\', risk_level = \\'high\\', safety_escalated = 1, safety_notes = ?, completed_at = ? \n",
    "                WHERE id = ?\n",
    "                \"\"\", (f\"Self-harm trigger word detected: '{final_ans}'\", datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\"), state[\"session_id\"]))\n",
    "                conn.commit()\n",
    "                conn.close()\n",
    "                \n",
    "                database.log_audit(st.session_state.user[\"id\"], \"safety_crisis_alert\", \"assessment_sessions\", state[\"session_id\"])\n",
    "                st.rerun()\n",
    "                return\n",
    "                \n",
    "            mapping = agents.AssessmentAgent.map_user_response(final_ans, q[\"options\"], q[\"scores\"])\n",
    "            m_idx = mapping.get(\"matched_index\", -1)\n",
    "            if m_idx == -1: \n",
    "                st.error(\"Answer unclear. Please select one of the direct buttons to map your response.\")\n",
    "                save_chat(state[\"session_id\"], \"assistant\", \"I couldn\\'t align that. Please select one of the direct options below.\")\n",
    "            else:\n",
    "                val = q[\"scores\"][m_idx]\n",
    "                opt_txt = q[\"options\"][m_idx]\n",
    "                conn = database.get_connection()\n",
    "                cursor = conn.cursor()\n",
    "                cursor.execute(\"\"\"\n",
    "                INSERT INTO assessment_responses (session_id, question_id, response_value, response_text)\n",
    "                VALUES (?, ?, ?, ?)\n",
    "                \"\"\", (state[\"session_id\"], q[\"id\"], val, opt_txt))\n",
    "                conn.commit()\n",
    "                conn.close()\n",
    "                \n",
    "                save_chat(state[\"session_id\"], \"assistant\", f\"Selected response: {opt_txt}\")\n",
    "                state[\"answers\"][q[\"id\"]] = val\n",
    "                state[\"q_idx\"] += 1\n",
    "                st.rerun()\n",
    "\n",
    "def render_patient_rag_view():\n",
    "    st.title(\"📚 CareMinds RAG Reference Center\")\n",
    "    query = st.text_input(\"Enter question to search indexed reference clinical documents:\")\n",
    "    if st.button(\"Query Index\"):\n",
    "        if not query: st.warning(\"Type a question.\")\n",
    "        else:\n",
    "            database.log_audit(st.session_state.user[\"id\"], \"knowledge_search\", \"faiss_index\", 0)\n",
    "            res = st.session_state.rag.search(query)\n",
    "            if not res: st.info(\"No database documents indexed. Upload PDFs in the Administrator screen.\")\n",
    "            else:\n",
    "                context = \"\"\n",
    "                for r in res: context += f\"[Doc: {r[\\'source\\']}, Page: {r[\\'page\\']}]\\\\n{r[\\'text\\']}\\\\n\\\\n\"\n",
    "                prompt = prompts.KNOWLEDGE_PROMPT.format(context=context, query=query)\n",
    "                ans = agents.gemini_client.generate(prompt)\n",
    "                st.subheader(\"Retrieved Grounded Answer:\")\n",
    "                st.write(ans)\n",
    "                st.subheader(\"Document Source Citations:\")\n",
    "                for r in res: st.markdown(f\"- **{r[\\'source\\']} (Page {r[\\'page\\']})** distance: `{r[\\'distance\\']:.4f}`\")\n",
    "\n",
    "def render_patient_progress_view():\n",
    "    st.title(\"📈 Evaluation Progress History\")\n",
    "    profile = agents.SecurityManager.get_patient_profile(st.session_state.user[\"id\"])\n",
    "    conn = database.get_connection()\n",
    "    cursor = conn.cursor()\n",
    "    cursor.execute(\"SELECT id, assessment_name, score, severity, risk_level, completed_at FROM assessment_sessions WHERE patient_id = ? AND status = \\'completed\\' ORDER BY completed_at ASC;\", (profile[\"patient_id\"],))\n",
    "    rows = [dict(r) for r in cursor.fetchall()]\n",
    "    conn.close()\n",
    "    if not rows: st.info(\"No completed assessments found.\")\n",
    "    else:\n",
    "        scales = list(set([r[\"assessment_name\"] for r in rows]))\n",
    "        selected = st.selectbox(\"Select scale to graph\", scales)\n",
    "        filtered = [r for r in rows if r[\"assessment_name\"] == selected]\n",
    "        dates = [f[\"completed_at\"][:10] for f in filtered]\n",
    "        scores = [f[\"score\"] for f in filtered]\n",
    "        \n",
    "        fig = go.Figure()\n",
    "        fig.add_trace(go.Scatter(x=dates, y=scores, mode=\"lines+markers\", name=\"Score\", line=dict(color=\"#3B82F6\", width=3)))\n",
    "        fig.update_layout(title=f\"Progress Trend - {selected}\", xaxis_title=\"Date\", yaxis_title=\"Score\", template=\"plotly_dark\")\n",
    "        st.plotly_chart(fig, use_container_width=True)\n",
    "        \n",
    "        st.subheader(\"Logs Table\")\n",
    "        for r in reversed(filtered):\n",
    "            with st.expander(f\"{r[\\'completed_at\\']} | Score: {r[\\'score\\']} ({r[\\'severity\\']})\"):\n",
    "                pdf_path = f\"reports/session_{r[\\'id\\']}_report.pdf\"\n",
    "                if os.path.exists(pdf_path):\n",
    "                    with open(pdf_path, \"rb\") as f:\n",
    "                        st.download_button(\"📥 Download report\", f, file_name=f\"report_{r[\\'id\\']}.pdf\", mime=\"application/pdf\", key=f\"progress_pdf_{r[\\'id\\']}\")\n",
    "\n",
    "def render_clinician_dashboard():\n",
    "    st.title(\"👩‍⚕️ Psychologist Patient Records\")\n",
    "    clinician_id = st.session_state.user[\"id\"]\n",
    "    \n",
    "    # Load clinician alerts (safety escalated)\n",
    "    conn = database.get_connection()\n",
    "    cursor = conn.cursor()\n",
    "    cursor.execute(\"\"\"\n",
    "        SELECT s.id, u.full_name, s.assessment_name, s.completed_at, s.safety_notes\n",
    "        FROM assessment_sessions s\n",
    "        JOIN patients p ON s.patient_id = p.id\n",
    "        JOIN users u ON p.user_id = u.id\n",
    "        WHERE p.assigned_psychologist_id = ? AND s.safety_escalated = 1\n",
    "        ORDER BY s.completed_at DESC\n",
    "    \"\"\", (clinician_id,))\n",
    "    alerts = cursor.fetchall()\n",
    "    conn.close()\n",
    "    \n",
    "    if alerts:\n",
    "        st.markdown(\\'<div class=\"alert-header\">⚠️ HIGH-RISK SAFETY CRITICAL EVENTS TRIGGERED:</div>\\', unsafe_allow_html=True)\n",
    "        for alert in alerts:\n",
    "            st.warning(f\"Patient: **{alert[\\'full_name\\']}** | Screening: **{alert[\\'assessment_name\\']}** on {alert[\\'completed_at\\']} | Message: `{alert[\\'safety_notes\\']}`\")\n",
    "            \n",
    "    # Patient dropdown list assigned to this clinician\n",
    "    conn = database.get_connection()\n",
    "    cursor = conn.cursor()\n",
    "    cursor.execute(\"\"\"\n",
    "        SELECT p.id as patient_id, u.full_name, p.dob, p.age, p.gender, p.consent_given \n",
    "        FROM patients p \n",
    "        JOIN users u ON p.user_id = u.id\n",
    "        WHERE p.assigned_psychologist_id = ?\n",
    "    \"\"\", (clinician_id,))\n",
    "    patients = [dict(r) for r in cursor.fetchall()]\n",
    "    conn.close()\n",
    "    \n",
    "    if not patients: \n",
    "        st.info(\"No patients assigned to your clinician account.\")\n",
    "        return\n",
    "        \n",
    "    p_map = {p[\"patient_id\"]: f\"{p[\\'full_name\\']} (Age: {p[\\'age\\']} | DOB: {p[\\'dob\\']})\" for p in patients}\n",
    "    selected_p = st.selectbox(\"Select patient profile\", list(p_map.keys()), format_func=lambda x: p_map[x])\n",
    "    \n",
    "    # Render patient progress visuals and logs\n",
    "    selected_p_details = next(p for p in patients if p[\"patient_id\"] == selected_p)\n",
    "    st.markdown(f\"\"\"\n",
    "    <div class=\\\"metric-card\\\">\n",
    "        <h4>Patient Case Details</h4>\n",
    "        <p><b>Name:</b> {selected_p_details[\\'full_name\\']} | <b>Gender:</b> {selected_p_details[\\'gender\\']} | <b>Consent:</b> {\\'Granted\\' if selected_p_details[\\'consent_given\\'] else \\'Not Provided\\'}</p>\n",
    "    </div>\n",
    "    \"\"\", unsafe_allow_html=True)\n",
    "    \n",
    "    # Visual dashboards\n",
    "    conn = database.get_connection()\n",
    "    cursor = conn.cursor()\n",
    "    cursor.execute(\"\"\"\n",
    "        SELECT s.id, s.assessment_name, s.score, s.severity, s.risk_level, s.completed_at, sum.summary_text, sum.clinician_notes, sum.action_items \n",
    "        FROM assessment_sessions s \n",
    "        LEFT JOIN session_summaries sum ON s.id = sum.session_id \n",
    "        WHERE s.patient_id = ? AND s.status = \\'completed\\'\n",
    "        ORDER BY s.completed_at DESC\n",
    "    \"\"\", (selected_p,))\n",
    "    sessions = [dict(r) for r in cursor.fetchall()]\n",
    "    conn.close()\n",
    "    \n",
    "    if not sessions:\n",
    "        st.info(\"No completed assessments for this patient.\")\n",
    "    else:\n",
    "        # Chart 1: Line Chart of Scores\n",
    "        st.subheader(\"Psychometric Scale Score Progress\")\n",
    "        graph_scales = list(set([s[\"assessment_name\"] for s in sessions]))\n",
    "        sel_graph_scale = st.selectbox(\"Choose screening scale\", graph_scales)\n",
    "        \n",
    "        scale_sessions = [s for s in sessions if s[\"assessment_name\"] == sel_graph_scale]\n",
    "        dates = [s[\"completed_at\"][:10] for s in scale_sessions]\n",
    "        scores = [s[\"score\"] for s in scale_sessions]\n",
    "        \n",
    "        fig_line = px.line(x=dates, y=scores, markers=True, title=f\"Symptom Trend - {sel_graph_scale}\")\n",
    "        fig_line.update_layout(template=\"plotly_dark\")\n",
    "        st.plotly_chart(fig_line, use_container_width=True)\n",
    "        \n",
    "        # Chart 2: Aggregated Clinician Statistics (assigned patients summary)\n",
    "        st.subheader(\"Overall assigned cases dashboard statistics\")\n",
    "        col_stat1, col_stat2 = st.columns(2)\n",
    "        \n",
    "        # Load global clinician stats\n",
    "        conn = database.get_connection()\n",
    "        cursor = conn.cursor()\n",
    "        cursor.execute(\"\"\"\n",
    "            SELECT s.risk_level, count(*) \n",
    "            FROM assessment_sessions s \n",
    "            JOIN patients p ON s.patient_id = p.id \n",
    "            WHERE p.assigned_psychologist_id = ? AND s.status = \\'completed\\' \n",
    "            GROUP BY s.risk_level\n",
    "        \"\"\", (clinician_id,))\n",
    "        risk_stats = cursor.fetchall()\n",
    "        \n",
    "        cursor.execute(\"\"\"\n",
    "            SELECT s.assessment_name, count(*) \n",
    "            FROM assessment_sessions s \n",
    "            JOIN patients p ON s.patient_id = p.id \n",
    "            WHERE p.assigned_psychologist_id = ? AND s.status = \\'completed\\' \n",
    "            GROUP BY s.assessment_name\n",
    "        \"\"\", (clinician_id,))\n",
    "        scale_stats = cursor.fetchall()\n",
    "        conn.close()\n",
    "        \n",
    "        with col_stat1:\n",
    "            if risk_stats:\n",
    "                fig_pie = px.pie(names=[r[0] for r in risk_stats], values=[r[1] for r in risk_stats], title=\"Case Risk Levels Distribution\")\n",
    "                fig_pie.update_layout(template=\"plotly_dark\")\n",
    "                st.plotly_chart(fig_pie, use_container_width=True)\n",
    "            else:\n",
    "                st.info(\"No risk data logged.\")\n",
    "        with col_stat2:\n",
    "            if scale_stats:\n",
    "                fig_bar = px.bar(x=[r[0] for r in scale_stats], y=[r[1] for r in scale_stats], title=\"Sessions Volume per Psychometric Scale\")\n",
    "                fig_bar.update_layout(template=\"plotly_dark\")\n",
    "                st.plotly_chart(fig_bar, use_container_width=True)\n",
    "            else:\n",
    "                st.info(\"No sessions volumes logged.\")\n",
    "                \n",
    "        st.subheader(\"Logs\")\n",
    "        for s in sessions:\n",
    "            with st.expander(f\"{s[\\'assessment_name\\']} on {s[\\'completed_at\\']} | Score: {s[\\'score\\']} ({s[\\'severity\\']}) Risk: {s[\\'risk_level\\'].upper()}\"):\n",
    "                st.write(f\"**Summary:** {s[\\'summary_text\\']}\")\n",
    "                st.markdown(s[\"clinician_notes\"] or \"SOAP details not calculated.\")\n",
    "                \n",
    "                # Exporters\n",
    "                pdf_path = f\"reports/session_{s[\\'id\\']}_report.pdf\"\n",
    "                if os.path.exists(pdf_path):\n",
    "                    with open(pdf_path, \"rb\") as f:\n",
    "                        st.download_button(\"Download PDF Record\", f, file_name=f\"report_{s[\\'id\\']}.pdf\", mime=\"application/pdf\", key=f\"clin_pdf_{s[\\'id\\']}\")\n",
    "                else:\n",
    "                    if st.button(\"Generate PDF Report Record\", key=f\"c_pdf_gen_{s[\\'id\\']}\"):\n",
    "                        report_generator.ReportGenerator.generate_assessment_report(s[\"id\"])\n",
    "                        st.success(\"Report generated. Reload page.\")\n",
    "                        \n",
    "                # JSON exporter\n",
    "                json_data = {\n",
    "                    \"session_id\": s[\"id\"],\n",
    "                    \"assessment\": s[\"assessment_name\"],\n",
    "                    \"score\": s[\"score\"],\n",
    "                    \"severity\": s[\"severity\"],\n",
    "                    \"risk_level\": s[\"risk_level\"],\n",
    "                    \"date\": s[\"completed_at\"],\n",
    "                    \"SOAP\": s[\"clinician_notes\"]\n",
    "                }\n",
    "                st.download_button(\"Export JSON Record\", json.dumps(json_data, indent=4), file_name=f\"report_{s[\\'id\\']}.json\", mime=\"application/json\", key=f\"clin_json_{s[\\'id\\']}\")\n",
    "\n",
    "def render_admin_pdfs():\n",
    "    st.title(\"🔑 Admin RAG reference library uploads\")\n",
    "    st.subheader(\"Incremental RAG PDF Indexer (MD5 hashing duplicate checks enabled)\")\n",
    "    \n",
    "    cat = st.selectbox(\"Select Knowledge Folder Category:\", [\"psychology\", \"cbt\", \"guidelines\", \"assessments\"])\n",
    "    uploaded = st.file_uploader(\"Choose a Clinical Reference PDF file to upload\", type=\"pdf\")\n",
    "    if uploaded is not None:\n",
    "        dest_folder = f\"knowledge_base/{cat}\"\n",
    "        dest = os.path.join(dest_folder, uploaded.name)\n",
    "        with open(dest, \"wb\") as f: \n",
    "            f.write(uploaded.getbuffer())\n",
    "        st.success(f\"Saved file to {dest}\")\n",
    "        \n",
    "        if st.button(\"Reindex RAG database with this PDF\"):\n",
    "            database.log_audit(st.session_state.user[\"id\"], \"document_upload\", \"faiss_index\", 0)\n",
    "            with st.spinner(\"Generating sentence transformer embeddings and updating FAISS index...\"):\n",
    "                chunks = st.session_state.rag.add_pdf(dest)\n",
    "            if chunks > 0: st.success(f\"Successfully indexed {chunks} new text chunks.\")\n",
    "            else: st.info(\"File is already indexed and unchanged (Skipped to prevent duplicate re-embedding).\")\n",
    "\n",
    "def main():\n",
    "    if not st.session_state.logged_in:\n",
    "        render_auth()\n",
    "    else:\n",
    "        nav = render_sidebar()\n",
    "        if nav == \"Intake & Consent\": render_intake()\n",
    "        elif nav == \"Assessment Center\": render_assessments()\n",
    "        elif nav == \"RAG Reference Help\": render_patient_rag_view()\n",
    "        elif nav == \"My Progress\": render_patient_progress_view()\n",
    "        elif nav == \"Patient Dashboard\": render_clinician_dashboard()\n",
    "        elif nav == \"RAG Reference Assistant\": render_patient_rag_view()\n",
    "        elif nav == \"Resource Administrator\": render_admin_pdfs()\n",
    "        elif nav == \"Database Auditor\":\n",
    "            st.title(\"🔑 Security audit logs\")\n",
    "            conn = database.get_connection()\n",
    "            cursor = conn.cursor()\n",
    "            cursor.execute(\"SELECT a.id, u.username, a.action, a.target_table, a.timestamp FROM audit_logs a LEFT JOIN users u ON a.user_id = u.id ORDER BY a.id DESC LIMIT 100;\")\n",
    "            logs = cursor.fetchall()\n",
    "            conn.close()\n",
    "            st.dataframe([dict(l) for l in logs], use_container_width=True)\n",
    "\n",
    "if __name__ == \\'__main__\\': main()\n",
    "''')\n",
    "print('app.py successfully generated.')\n"
]

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": cell_8_source_lines
})

# ==========================================================
# CELL 9: Authentication & Security Validation
# ==========================================================
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Cell 9: Authentication & Security Validation\n",
        "# Verify security tables and password verification utility on SQLite\n",
        "import sqlite3\n",
        "import database\n",
        "import agents\n",
        "\n",
        "conn = database.get_connection()\n",
        "cursor = conn.cursor()\n",
        "cursor.execute('SELECT id, username, role, full_name FROM users;')\n",
        "users = cursor.fetchall()\n",
        "conn.close()\n",
        "\n",
        "print(f'System security checks passed. Registered accounts: {len(users)}')\n",
        "for u in users:\n",
        "    print(f'- ID: {u[0]} | Username: {u[1]} | Role: {u[2]} | Name: {u[3]}')\n"
    ]
})

# ==========================================================
# CELL 10: PDF reports
# ==========================================================
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Cell 10: Report Generator (PDF)\n",
        "# Writes the report_generator.py file to disk and loads it\n",
        "with open('report_generator.py', 'w', encoding='utf-8') as f:\n",
        "    f.write('''import os\n",
        "import sqlite3\n",
        "import json\n",
        "from reportlab.lib.pagesizes import letter\n",
        "from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle\n",
        "from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle\n",
        "from reportlab.lib import colors\n",
        "import database\n",
        "\n",
        "class ReportGenerator:\n",
        "    @staticmethod\n",
        "    def generate_assessment_report(session_id):\n",
        "        conn = database.get_connection()\n",
        "        cursor = conn.cursor()\n",
        "        cursor.execute(\"\"\"\n",
        "            SELECT \n",
        "                s.id as session_id,\n",
        "                s.assessment_name,\n",
        "                s.status,\n",
        "                s.score,\n",
        "                s.severity,\n",
        "                s.risk_level,\n",
        "                s.safety_escalated,\n",
        "                s.safety_notes,\n",
        "                s.started_at,\n",
        "                s.completed_at,\n",
        "                p.id as patient_id,\n",
        "                p.dob,\n",
        "                p.age,\n",
        "                p.gender,\n",
        "                p.phone,\n",
        "                u.full_name as patient_name,\n",
        "                u.email as patient_email\n",
        "            FROM assessment_sessions s\n",
        "            JOIN patients p ON s.patient_id = p.id\n",
        "            JOIN users u ON p.user_id = u.id\n",
        "            WHERE s.id = ?\n",
        "        \"\"\", (session_id,))\n",
        "        session = cursor.fetchone()\n",
        "        if not session:\n",
        "            conn.close()\n",
        "            raise ValueError(f\"Session with ID {session_id} not found.\")\n",
        "        \n",
        "        cursor.execute(\"\"\"\n",
        "            SELECT summary_text, clinician_notes, action_items\n",
        "            FROM session_summaries\n",
        "            WHERE session_id = ?\n",
        "        \"\"\", (session_id,))\n",
        "        summary = cursor.fetchone()\n",
        "        \n",
        "        cursor.execute(\"\"\"\n",
        "            SELECT question_id, response_value, response_text\n",
        "            FROM assessment_responses\n",
        "            WHERE session_id = ?\n",
        "            ORDER BY id ASC\n",
        "        \"\"\", (session_id,))\n",
        "        responses = cursor.fetchall()\n",
        "        conn.close()\n",
        "        \n",
        "        os.makedirs(\"reports\", exist_ok=True)\n",
        "        pdf_path = f\"reports/session_{session_id}_report.pdf\"\n",
        "        doc = SimpleDocTemplate(pdf_path, pagesize=letter,\n",
        "                                rightMargin=40, leftMargin=40,\n",
        "                                topMargin=40, bottomMargin=40)\n",
        "        story = []\n",
        "        styles = getSampleStyleSheet()\n",
        "        title_style = ParagraphStyle(\n",
        "            \\'ReportTitle\\',\n",
        "            parent=styles[\\'Heading1\\'],\n",
        "            fontSize=24,\n",
        "            leading=28,\n",
        "            textColor=colors.HexColor(\\'#1E3A8A\\'),\n",
        "            spaceAfter=15\n",
        "        )\n",
        "        section_style = ParagraphStyle(\n",
        "            \\'ReportSection\\',\n",
        "            parent=styles[\\'Heading2\\'],\n",
        "            fontSize=16,\n",
        "            leading=20,\n",
        "            textColor=colors.HexColor(\\'#0F766E\\'),\n",
        "            spaceBefore=12,\n",
        "            spaceAfter=6\n",
        "        )\n",
        "        normal_style = ParagraphStyle(\n",
        "            \\'ReportNormal\\',\n",
        "            parent=styles[\\'Normal\\'],\n",
        "            fontSize=10,\n",
        "            leading=14,\n",
        "            textColor=colors.HexColor(\\'#374151\\')\n",
        "        )\n",
        "        bold_style = ParagraphStyle(\n",
        "            \\'ReportBold\\',\n",
        "            parent=normal_style,\n",
        "            fontName=\\'Helvetica-Bold\\'\n",
        "        )\n",
        "        story.append(Paragraph(\"CareMinds AI Clinical Assessment Report\", title_style))\n",
        "        story.append(Paragraph(f\"Generated on: {session[\\'completed_at\\'] or session[\\'started_at\\']}\", normal_style))\n",
        "        story.append(Spacer(1, 10))\n",
        "        \n",
        "        info_data = [\n",
        "            [Paragraph(\"Patient Name:\", bold_style), Paragraph(str(session[\\'patient_name\\']), normal_style),\n",
        "             Paragraph(\"Assessment:\", bold_style), Paragraph(str(session[\\'assessment_name\\']), normal_style)],\n",
        "            [Paragraph(\"Date of Birth:\", bold_style), Paragraph(str(session[\\'dob\\']), normal_style),\n",
        "             Paragraph(\"Started At:\", bold_style), Paragraph(str(session[\\'started_at\\']), normal_style)],\n",
        "            [Paragraph(\"Age / Gender:\", bold_style), Paragraph(f\"{session[\\'age\\']} / {session[\\'gender\\']}\", normal_style),\n",
        "             Paragraph(\"Completed At:\", bold_style), Paragraph(str(session[\\'completed_at\\'] or \\'N/A\\'), normal_style)],\n",
        "            [Paragraph(\"Phone / Email:\", bold_style), Paragraph(f\"{session[\\'phone\\']} / {session[\\'patient_email\\']}\", normal_style),\n",
        "             Paragraph(\"Status:\", bold_style), Paragraph(str(session[\\'status\\']).upper(), normal_style)]\n",
        "        ]\n",
        "        info_table = Table(info_data, colWidths=[90, 170, 90, 170])\n",
        "        info_table.setStyle(TableStyle([\n",
        "            (\\'BACKGROUND\\', (0,0), (-1,-1), colors.HexColor(\\'#F3F4F6\\')),\n",
        "            (\\'ALIGN\\', (0,0), (-1,-1), \\'LEFT\\'),\n",
        "            (\\'VALIGN\\', (0,0), (-1,-1), \\'MIDDLE\\'),\n",
        "            (\\'GRID\\', (0,0), (-1,-1), 0.5, colors.HexColor(\\'#D1D5DB\\')),\n",
        "            (\\'TOPPADDING\\', (0,0), (-1,-1), 6),\n",
        "            (\\'BOTTOMPADDING\\', (0,0), (-1,-1), 6),\n",
        "            (\\'LEFTPADDING\\', (0,0), (-1,-1), 8),\n",
        "            (\\'RIGHTPADDING\\', (0,0), (-1,-1), 8),\n",
        "        ]))\n",
        "        story.append(info_table)\n",
        "        story.append(Spacer(1, 15))\n",
        "        \n",
        "        score = session[\\'score\\'] if session[\\'score\\'] is not None else \\'N/A\\'\n",
        "        severity = session[\\'severity\\'] or \\'N/A\\'\n",
        "        risk_level = session[\\'risk_level\\'] or \\'low\\'\n",
        "        safety_escalated = \"YES (🚨 CRITICAL ESCALATION)\" if session[\\'safety_escalated\\'] else \"NO\"\n",
        "        \n",
        "        metrics_data = [\n",
        "            [Paragraph(\"Calculated Score\", bold_style), Paragraph(\"Severity Classification\", bold_style), Paragraph(\"Safety Risk Flag\", bold_style), Paragraph(\"Safety Escalated\", bold_style)],\n",
        "            [Paragraph(f\"<font size=14 color=\\'#1E3A8A\\'><b>{score}</b></font>\", normal_style),\n",
        "             Paragraph(f\"<b>{severity}</b>\", normal_style),\n",
        "             Paragraph(f\"<b>{risk_level.upper()}</b>\", normal_style),\n",
        "             Paragraph(f\"<b>{safety_escalated}</b>\", normal_style)]\n",
        "        ]\n",
        "        metrics_table = Table(metrics_data, colWidths=[130, 150, 120, 120])\n",
        "        metrics_table.setStyle(TableStyle([\n",
        "            (\\'BACKGROUND\\', (0,0), (-1,0), colors.HexColor(\\'#E5E7EB\\')),\n",
        "            (\\'ALIGN\\', (0,0), (-1,-1), \\'CENTER\\'),\n",
        "            (\\'VALIGN\\', (0,0), (-1,-1), \\'MIDDLE\\'),\n",
        "            (\\'GRID\\', (0,0), (-1,-1), 1, colors.HexColor(\\'#9CA3AF\\')),\n",
        "            (\\'TOPPADDING\\', (0,0), (-1,-1), 8),\n",
        "            (\\'BOTTOMPADDING\\', (0,0), (-1,-1), 8),\n",
        "        ]))\n",
        "        story.append(metrics_table)\n",
        "        story.append(Spacer(1, 15))\n",
        "        \n",
        "        if session[\\'safety_escalated\\'] or (session[\\'safety_notes\\'] and len(session[\\'safety_notes\\']) > 0):\n",
        "            story.append(Paragraph(\"🚨 Safety & Crisis Intervention Notes\", section_style))\n",
        "            safety_notes_text = session[\\'safety_notes\\'] or \"Self-harm / Crisis indicators flagged during session.\"\n",
        "            story.append(Paragraph(f\"<b>Alert Notes:</b> {safety_notes_text}\", ParagraphStyle(\\'SafetyText\\', parent=normal_style, textColor=colors.HexColor(\\'#991B1B\\'))))\n",
        "            story.append(Spacer(1, 10))\n",
        "        \n",
        "        if summary:\n",
        "            story.append(Paragraph(\"📝 Clinical Summary\", section_style))\n",
        "            story.append(Paragraph(str(summary[\\'summary_text\\']), normal_style))\n",
        "            story.append(Spacer(1, 10))\n",
        "            \n",
        "            story.append(Paragraph(\"🩺 Clinician SOAP Notes\", section_style))\n",
        "            soap_lines = str(summary[\\'clinician_notes\\']).split(\\'\\\\n\\')\n",
        "            for line in soap_lines:\n",
        "                if line.strip():\n",
        "                    story.append(Paragraph(line, normal_style))\n",
        "            story.append(Spacer(1, 10))\n",
        "            \n",
        "            story.append(Paragraph(\"📋 Clinical Action Items\", section_style))\n",
        "            action_lines = str(summary[\\'action_items\\']).split(\\'\\\\n\\')\n",
        "            for line in action_lines:\n",
        "                if line.strip():\n",
        "                    story.append(Paragraph(line, normal_style))\n",
        "            story.append(Spacer(1, 15))\n",
        "        \n",
        "        story.append(Paragraph(\"📊 Detailed Patient Responses\", section_style))\n",
        "        resp_headers = [Paragraph(\"<b>Question ID</b>\", normal_style), Paragraph(\"<b>Question Text / Response</b>\", normal_style), Paragraph(\"<b>Value</b>\", normal_style)]\n",
        "        resp_rows = [resp_headers]\n",
        "        \n",
        "        scale_key = None\n",
        "        if \\'phq\\' in session[\\'assessment_name\\'].lower():\n",
        "            scale_key = \\'phq9\\'\n",
        "        elif \\'gad\\' in session[\\'assessment_name\\'].lower():\n",
        "            scale_key = \\'gad7\\'\n",
        "        elif \\'who\\' in session[\\'assessment_name\\'].lower():\n",
        "            scale_key = \\'who5\\'\n",
        "        elif \\'pss\\' in session[\\'assessment_name\\'].lower() or \\'stress\\' in session[\\'assessment_name\\'].lower():\n",
        "            scale_key = \\'pss10\\'\n",
        "            \n",
        "        questions_dict = {}\n",
        "        if scale_key:\n",
        "            try:\n",
        "                with open(f\"data/assessments/{scale_key}.json\", \"r\", encoding=\"utf-8\") as f_q:\n",
        "                    import json as j_q\n",
        "                    scale_data = j_q.load(f_q)\n",
        "                    for q in scale_data.get(\"questions\", []):\n",
        "                        questions_dict[q[\"id\"]] = q[\"text\"]\n",
        "            except Exception as e:\n",
        "                print(f\"Could not load question map: {e}\")\n",
        "                \n",
        "        for r in responses:\n",
        "            q_id = r[\\'question_id\\']\n",
        "            q_text = questions_dict.get(q_id, \"Question text not found in local scale files.\")\n",
        "            resp_val = r[\\'response_value\\']\n",
        "            resp_txt = r[\\'response_text\\']\n",
        "            \n",
        "            resp_rows.append([\n",
        "                Paragraph(str(q_id), normal_style),\n",
        "                Paragraph(f\"<b>Q:</b> {q_text}<br/><b>A:</b> {resp_txt}\", normal_style),\n",
        "                Paragraph(str(resp_val), normal_style)\n",
        "            ])\n",
        "            \n",
        "        resp_table = Table(resp_rows, colWidths=[60, 410, 50])\n",
        "        resp_table.setStyle(TableStyle([\n",
        "            (\\'BACKGROUND\\', (0,0), (-1,0), colors.HexColor(\\'#F3F4F6\\')),\n",
        "            (\\'ALIGN\\', (0,0), (0,-1), \\'CENTER\\'),\n",
        "            (\\'ALIGN\\', (2,0), (2,-1), \\'CENTER\\'),\n",
        "            (\\'VALIGN\\', (0,0), (-1,-1), \\'TOP\\'),\n",
        "            (\\'GRID\\', (0,0), (-1,-1), 0.5, colors.HexColor(\\'#E5E7EB\\')),\n",
        "            (\\'TOPPADDING\\', (0,0), (-1,-1), 5),\n",
        "            (\\'BOTTOMPADDING\\', (0,0), (-1,-1), 5),\n",
        "        ]))\n",
        "        story.append(resp_table)\n",
        "        doc.build(story)\n",
        "        print(\"Clinical PDF Report successfully generated.\")\n",
        "''')\n",
        "import report_generator\n",
        "print('report_generator.py module loaded successfully.')\n"
    ]
})

# ==========================================================
# CELL 11: Dashboard & Plotly
# ==========================================================
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Cell 11: Dashboard and Plotly Chart Tests\n",
        "# Renders a sample trend line mockup in the notebook context\n",
        "import plotly.graph_objects as go\n",
        "from datetime import datetime, timedelta\n",
        "\n",
        "start_date = datetime.now() - timedelta(weeks=4)\n",
        "dates = [(start_date + timedelta(weeks=i)).strftime('%Y-%m-%d') for i in range(5)]\n",
        "scores = [15, 12, 10, 8, 5]  # Sample anxiety reduction pattern\n",
        "\n",
        "fig = go.Figure()\n",
        "fig.add_trace(go.Scatter(x=dates, y=scores, mode='lines+markers', name='GAD-7 Score', line=dict(color='#3B82F6', width=3)))\n",
        "fig.update_layout(\n",
        "    title='GAD-7 Score Clinical Progress Sample Graph',\n",
        "    xaxis_title='Evaluation Date',\n",
        "    yaxis_title='Score Value',\n",
        "    template='plotly_dark'\n",
        ")\n",
        "fig.show()\n"
    ]
})

# ==========================================================
# CELL 12: Tunnel & Run Streamlit (Launch Streamlit with Ngrok)
# ==========================================================
cell_12_lines = [
    "# Cell 12: Launch Streamlit with Ngrok\n",
    "# Exposes port 8501 using pyngrok. Prompts for key/token if not preset\n",
    "import os\n",
    "import subprocess\n",
    "import time\n",
    "from pyngrok import ngrok\n",
    "\n",
    "groq_key = os.environ.get('GROQ_API_KEY', '')\n",
    "if not groq_key:\n",
    "    groq_key = input('Please enter your Groq API Key: ').strip()\n",
    "    os.environ['GROQ_API_KEY'] = groq_key\n",
    "\n",
    "ngrok_token = os.environ.get('NGROK_AUTHTOKEN', '')\n",
    "if not ngrok_token:\n",
    "    ngrok_token = input('Please enter your Ngrok Authtoken: ').strip()\n",
    "    ngrok.set_auth_token(ngrok_token)\n",
    "else:\n",
    "    ngrok.set_auth_token(ngrok_token)\n",
    "\n",
    "print('Starting Streamlit process on port 8501...')\n",
    "proc = subprocess.Popen(\n",
    "    ['streamlit', 'run', 'app.py', '--server.port', '8501', '--server.address', 'localhost'],\n",
    "    stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True\n",
    ")\n",
    "\n",
    "time.sleep(3)\n",
    "if proc.poll() is not None:\n",
    "    print('Streamlit failed to start. Logs:')\n",
    "    stdout, stderr = proc.communicate()\n",
    "    print(stdout, stderr)\n",
    "else:\n",
    "    print('Streamlit active. Connecting Ngrok tunnel...')\n",
    "    try:\n",
    "        tunnel = ngrok.connect(8501)\n",
    "        print('\\n' + '='*55)\n",
    "        print(f'🚀 CareMinds Platform is active! Exposing public URL:')\n",
    "        print(f'👉 {tunnel.public_url} 👈')\n",
    "        print('='*55 + '\\n')\n",
    "        print('Seeded login credentials:')\n",
    "        print('- Patient User:      john_doe  /  patient123')\n",
    "        print('- Clinical Psych:    dr_smith  /  therapist123')\n",
    "        print('- Admin User:        admin     /  admin123')\n",
    "        print('\\nLeave this cell running to sustain the public link.')\n",
    "    except Exception as e:\n",
    "        print(f'Tunnel failure: {e}')\n"
]

cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": cell_12_lines
})

# ==========================================================
# ASSEMBLE & DUMP IPYNB FILE
# ==========================================================
notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 0
}

notebook_path = "C:/Users/hariv/Downloads/pysci/mental_health_platform.ipynb"
with open(notebook_path, "w") as f:
    json.dump(notebook, f, indent=2)

print(f"Notebook successfully written to {notebook_path}")
